const questions = [

    { letter: 'a', answer: ['Abducir', 'Agenda', 'Anticuario'], status: 0, question: ['CON LA A. Dicho de una supuesta criatura extraterrestre: Apoderarse de alguien', 'CON LA A. Libro o cuaderno en el que se apunta para no olvidarlo aquello que se ha de hacer', 'CON LA A. Persona que colecciona o negocia con antigüedades'] },
    { letter: 'b', answer: ['Bingo', 'Bonanza', 'Biberón'], status: 0, question: ["CON LA B. Juego que ha sacado de quicio a todos los 'Skylabers' en las sesiones de pre curso", 'CON LA B. Prosperidad', 'CON LA B. Utensilio para la lactancia artificial que consiste en una botella pequeña con una tetina de goma'] },
    { letter: 'c', answer: ['Churumbel', 'Caracol', 'Capo'], status: 0, question: ['CON LA C. Niño, crío, bebé', 'CON LA C. Nombre del molusco gasterópodo terrestre de corte en espiral cuya carne puede comerse', 'CON LA C. Jefe de la mafia, especialmente de narcotraficantes'] },
    { letter: 'd', answer: ['Diarrea', 'Dormir', 'Desodorante'], status: 0, question: ['CON LA D. Anormalidad en la función del aparato digestivo caracterizada por frecuentes evacuaciones y su consistencia líquida', 'CON LA D. Estar en aquel reposo que consiste en la inacción o suspensión de los sentidos y de todo movimiento voluntario', 'CON LA D. Producto que se utiliza para suprimir el olor corporal o de algún recinto'] },
    { letter: 'e', answer: ['Ectoplasma', 'Entrecot', 'Efímero'], status: 0, question: ['CON LA E. Gelatinoso y se encuentra debajo de la membrana plasmática. Los cazafantasmas medían su radiación', 'CON LA E. Trozo de carne sacado de entre costilla y costilla de la res', 'CON LA E. Pasajero, de corta duración'] },
    { letter: 'f', answer: ['Fácil', 'Farhadi', 'Faja'], status: 0, question: ['CON LA F. Que no requiere gran esfuerzo, capacidad o dificultad', 'CON LA F. Apellido del cineasta que dirigó la película El Viajante que obtuvo el oscar a la mejor película de habla no inglesa en 2017', 'CON LA F. Prenda interior elástica que ciñe la cintura, o la cintura y las caderas'] },
    { letter: 'g', answer: ['Galaxia', 'Gorgorito', 'Gominola'], status: 0, question: ['CON LA G. Conjunto enorme de estrellas, polvo interestelar, gases y partículas', 'CON LA G. Coloquialmente quiebro que se hace con la voz con la garganta al cantar', 'CON LA G. Golosina blanca masticable, generalmente recubierta de azúcar'] },
    { letter: 'h', answer: ['Harakiri', 'Hidroavión', 'Historia'], status: 0, question: ['CON LA H. Suicidio ritual japonés por desentrañamiento', 'CON LA H. Avión que lleva en lugar de ruedas uno o cuatro flotadores para posarse sobre el agua', 'CON LA H. Conjunto de todos los hechos ocurridos en tiempos pasados'] },
    { letter: 'i', answer: ['Iglesia', 'Inapetencia', 'Indignar'], status: 0, question: ['CON LA I. Templo cristiano', 'CON LA I. Falta de gana de comer', 'CON LA I. Irritar, enfadar vehementemente a alguien'] },
    { letter: 'j', answer: ['Jabalí', 'Jardinería', 'Jubilado'], status: 0, question: ["CON LA J. Variedad salvaje del cerdo que sale en la película 'El Rey León', de nombre Pumba", 'CON LA J. Arte y oficio del jardinero', 'CON LA J. Persona que ha dejado de trabajar y percibe una pensión'] },
    { letter: 'k', answer: ['Kamikaze', 'Okupa', 'Kentucky'], status: 0, question: ['CON LA K. Persona que se juega la vida realizando una acción temeraria', 'CONTIENE LA K. Persona que se instala en una vivienda o local deshabitado, sin consentimiento del propietario', 'CON LA K. Primera palabra del acrónimo que da nombre a la famosa cadena de restaurantes de comida rápida KFC'] },
    { letter: 'l', answer: ['Licántropo', 'Lobera', 'Linaje'], status: 0, question: ['CON LA L. Hombre lobo', 'CON LA L. Guarida de lobos', 'CON LA L. Ascendencia o descendencia de una familia, especialmente noble'] },
    { letter: 'm', answer: ['Misántropo', 'Mentira', 'Madriguera'], status: 0, question: ['CON LA M. Persona que huye del trato con otras personas o siente gran aversión hacia ellas', 'CON LA M. Cosa que se utiliza por el camino que no es verdad con la intención de que sea creída', 'CON LA M. Cueva en la que habitan ciertos animales, especialmente los conejos'] },
    { letter: 'n', answer: ['Necedad', 'Nativo', 'Nacionalidad'], status: 0, question: ['CON LA N. Demostración de poca inteligencia', 'CON LA N. Se aplica al que ha nacido en el lugar de que se trata', 'CON LA N. Estado propio de la persona nacida o naturalizada en una nación'] },
    { letter: 'ñ', answer: ['Señal', 'Hogaño', 'Soñar'], status: 0, question: ['CONTIENE LA Ñ. Indicio que permite deducir algo de lo que no se tiene un conocimiento directo.', 'CONTIENE LA Ñ. De tiempo que indica en esta época diferencia de antaño en época inferior.', 'CONTIENE LA Ñ. Representarse en la fantasía imágenes o sucesos mientras se duerme'] },
    { letter: 'o', answer: ['Orco', 'Órgano', 'Onírico'], status: 0, question: ['CON LA O. Humanoide fantástico de apariencia terrible y bestial, piel de color verde creada por el escritor Tolkien', 'CON LA O. De las partes del pulpo, animal o vegetal que ejercen una función', 'CON LA O. Perteneciente o relativo a los sueños'] },
    { letter: 'p', answer: ['Protoss', 'Plotino', 'Promover'], status: 0, question: ['CON LA P. Raza ancestral tecnológicamente avanzada que se caracteriza por sus grandes poderes psíonicos del videojuego StarCraft', 'CON LA P. Filósofo romano máximo representante de la escuela neoplatónica y discípulo de Ammonio Sacas de Alejandría', 'CON LA P. Iniciar o impulsar una idea o proyecto procurando su logro'] },
    { letter: 'q', answer: ['Queso', 'Chisquero', 'Delinquir'], status: 0, question: ['CON LA Q. Producto obtenido por la maduración de la cuajada de la leche', 'CONTIENE LA Q. Encendedor antiguo de bolsillo', 'CONTIENE LA Q. Cometer delito'] },
    { letter: 'r', answer: ['Ratón', 'Ráfaga', 'Reciclar'], status: 0, question: ['CON LA R. Roedor', 'CON LA R. Viento fuerte, resentido y de corta duración', 'CON LA R. Someter material usado a un proceso para que se pueda volver a utilizar'] },
    { letter: 's', answer: ['Stackoverflow', 'Simple', 'Suprimir'], status: 0, question: ['CON LA S. Comunidad salvadora de todo desarrollador informático', 'CON LA S. Se aplica a lo que no tiene complicación', 'CON LA S. Hacer cesar, hacer desaparecer, anular'] },
    { letter: 't', answer: ['Terminator', 'Trece', 'Tipi'], status: 0, question: ['CON LA T. Película del director James Cameron que consolidó a Arnold Schwarzenegger como actor en 1984', 'CON LA T. Número cardinal equivalente a 10 + 3', 'CON LA T. Tienda de piel de forma cónica que utilizaban como vivienda los indios de las praderas de América del Norte'] },
    { letter: 'u', answer: ['Unamuno', 'Uderzo', 'Urgencia'], status: 0, question: ["CON LA U. Escritor y filósofo español de la generación del 98 autor del libro 'Niebla' en 1914", 'CON LA U. Apellido del dibujante y guionista francés autor de la serie Asterix', 'CON LA U. Necesidad o falta apremiante, inmediata obligación de hacer algo'] },
    { letter: 'v', answer: ['Vikingos', 'Verde', 'Vivienda'], status: 0, question: ['CON LA V. Nombre dado a los miembros de los pueblos nórdicos originarios de Escandinavia, famosos por sus incursiones y pillajes en Europa', 'CON LA V. Se aplica el color perfectamente al de la hierba fresca o la esmeralda', 'CON LA V. Lugar cerrado y cubierto construido para ser habitado por personas'] },
    { letter: 'w', answer: ['Sandwich', 'Darwin', 'Walter'], status: 0, question: ['CONTIENE LA W. Emparedado hecho con dos rebanadas de pan entre las cuales se coloca jamón y queso', 'CONTIENE LA W. Creador de la teoría de la evolución.', 'CON LA W. Nombre de pila del protagonista de la serie Breaking Bad'] },
    { letter: 'x', answer: ['Botox', 'Exégesis', 'Exaltar'], status: 0, question: ['CONTIENE LA X. Toxina bacteriana utilizada en cirugía estética', 'CONTIENE LA X. Explicación o interpretación particularmente de los libros de la Biblia', 'CONTIENE LA X. Avivar o aumentar un sentimiento o pasión, realzar el mérito o las cualidades de alguien'] },
    { letter: 'y', answer: ['Peyote', 'Moncayo', 'Ensayar'], status: 0, question: ['CONTIENE LA Y. Pequeño cactus conocido por sus alcaloides psicoactivos utilizado de forma ritual y medicinal por indígenas americanos', 'CONTIENE LA Y. Nombre de la montaña más alta del sistema ibérico', 'CONTIENE LA Y. Preparar el montaje y ejecución de un espectáculo antes de ofrecerlo al público'] },
    { letter: 'z', answer: ['Zen', 'Zodiacal', 'Zumbado'], status: 0, question: ['CON LA Z. Escuela de budismo que busca la experiencia de la sabiduría más allá del discurso racional', 'CON LA Z. Perteneciente o relativo al zodíaco', 'CON LA Z. Participio del verbo zumbar'] },

];

export default questions;